# @package _global_

defaults:
  - override /data: libero
  - override /model: enfold
  - _self_

batch_size: 8
num_workers: 8

lr_scheduler_type: cosine
learning_rate: 1.0e-4
num_epochs: 10
max_steps: null
log_every: 10
save_every: 2000
eval_every: 200

gradient_accumulation_steps: 2
weight_decay: 1.0e-2
resume: null

model:
  prediction_head_config:
    condition_dim: 5120
    num_layers: 10
  action_head_config:
    num_layers: 10
